### PR TITLE
 docs: use new standard Open edX for documentation 

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
**Description:** 
This PR generates the new files structure for docs proposed in [this](https://docs.openedx.org/en/latest/developers/how-tos/add-sphinx-docs-to-a-repo.html) how-to by the community members. This is how it looks rendered with a few modifications:
image

**ISSUE:** 
https://github.com/openedx/openedx-filters/issues/41

**Dependencies:** 
None 

**Merge deadline:** 
ASAP

**Installation instructions:** 
 Just documentation

**Testing instructions:**
 Just documentation

**Reviewers:**
- [ ] @felipemontoya 

**Merge checklist:**
- [ ] All reviewers approved
- [ ] CI build is green
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [ ] Commits are squashed

**Post merge:**
- [ ] Create a tag
- [ ] Check new version is pushed to PyPI after tag-triggered build is 
      finished.
- [ ] Delete working branch (if not needed anymore)

**Author concerns:** 
None for now

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi!

As a core committer in this repo, you can merge this once the pull request is approved per the [core committer reviewer requirements](https://openedx.atlassian.net/wiki/spaces/COMM/pages/1529675973/Open+edX+Core+Committers#Reviews-and-Ownership) and according to the agreement with your edX Champion.

**Review by felipemontoya — APPROVED** [review]
This changes seem full reasonable to me. They affect the build format and not the content

**Comment by mphilbrick211** [comment]
Hi @mariajgrimaldi - just checking to see if this is ready to merge?

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-filters&entry.867055334=https://github.com/openedx/openedx-filters/pull/63&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2023-01-26+13:10&entry.1917517419=2023-02-07+22:25&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by pomegranited** [comment]
Hi @mariajgrimaldi ! Where can I see the newly rendered docs for this repo since this change was made? The [readthedocs](https://openedx-filters.readthedocs.io/en/latest/) link on the [README](https://github.com/openedx/openedx-filters#documentation) doesn't work anymore :(

**Pull request merged**
