### PR TITLE
fix: Install pip and pip-tools in upgrade script

### PR DESCRIPTION
**Pull request by Jawayria**
Updated the upgrade target script to check the compatibility of upgraded pip and pip-tools versions. For reference, look at this https://github.com/openedx/edx-repo-health/pull/271 for new check added in edx-repo-health.

### CODE REVIEW

**Comment by mariajgrimaldi** [comment]
Thanks for your contribution! I'll be reviewing this as soon as possible :)

**Comment by Jawayria** [comment]
Usama Sadiq will carry this forward

**Comment by mariajgrimaldi** [comment]
Hello! You can make the changes on this PR here also: https://github.com/openedx/openedx-events/pull/70, including this fix I added [here](https://github.com/openedx/openedx-events/pull/70#issuecomment-1224269632).

**Comment by mariajgrimaldi** [comment]
Hello @UsamaSadiq! Are you taking this up as well?

**Comment by UsamaSadiq** [comment]
Yes, I'll be working on this PR too. I'll update the PR with required changes soon.

**Comment by UsamaSadiq** [comment]
This PR can be closed in the favour of the new PR.

**Comment by mariajgrimaldi** [comment]
@UsamaSadiq: hello! do you need help opening the new PR? I can work on it since this is an important fix for us.

**Comment by openedx-webhooks** [comment]
Although this pull request is already closed,  I'm still watching it for updates.

There is nothing you have to do. No action is needed from your side.  Thanks.

**Pull request closed without merging**
