### PR TITLE
docs: add configuration for automatic filters docs generation

### PR DESCRIPTION
**Pull request by mariajgrimaldi**
### Description
This PR adds the necessary configuration for automatic docs generation based on Open edX Filters classes, you can see the docs generated here: https://docsopenedxorg--173.org.readthedocs.build/projects/openedx-filters/en/173/

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @mariajgrimaldi! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by mariajgrimaldi** [comment]
Hi @Ian2012 @felipemontoya! I'll also update the docstrings so they have more meaningful content. But in the meantime, could you let me know what you think about the content? Is it enough? What else should we add? Thanks!

**Review by Ian2012 — APPROVED** [review]
LGTM

**Review by felipemontoya — APPROVED** [review]
Working as advertised. I think this is good for merging.

Another thing we should do is to make available the different versions on the docs page, but that is not related to this specific work.

**Comment by mariajgrimaldi** [comment]
Since I'm only changing documentation, I'll be merging as is.

**Comment by openedx-webhooks** [comment]
@mariajgrimaldi 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/openedx-filters&entry.867055334=https://github.com/openedx/openedx-filters/pull/173&entry.1484655318=https://github.com/mariajgrimaldi&entry.752974735=2024-06-04+19:20&entry.1917517419=2024-06-21+21:42&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
